#!/bin/sh

# Autostart
xrandr --output eDP-1 --mode 1920x1080 --rate 60.01
xrandr --output eDP-2 --mode 1920x1080 --rate 60.01
xrandr --output DP-0 --mode 1920x1080 --rate 60.01
xrandr --output HDMI-0 --mode 1920x1080 --rate 60.01
xset s off
xset s noblank
xset -dpms
# xss-lock -- betterlockscreen &
xsetroot -cursor_name left_ptr
xsetroot -xcf /run/current-system/sw/share/icons/Bibata-Modern-Classic/cursors/left_ptr 30
wal -R &
pgrep -x sxhkd >/dev/null || sxhkd &
pkill picom
picom &
libinput-gestures &
jamesdsp --tray &
~/snix/scripts/launch-poly
xset r rate 220 40

# Monitor
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d I II III IV V VI VII VIII IX X

# Window Information
bspc config border_width 2
bspc config window_gap 3
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1    5"
bspc config presel_feedback_color "$color    1"

# Rules
bspc rule -a mumble state=floating follow=on focus=on
