#!/bin/sh

# Autostart
pgrep -x sxhkd >/dev/null || sxhkd &
pkill picom
picom &
# feh --bg-fill ~/Wallpapers/
~/.config/polybar/launch.sh

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window Information
bspc config border_width 1
bspc config window_gap 2
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Rules
bspc rule -a mumble state=floating follow=on focus=on
