#!/bin/sh

# Autostart
xrandr -s 1920x1080_60.01
xset s off
xset s noblank
xset -dpms
# xss-lock -- betterlockscreen &
xsetroot -cursor_name left_ptr
xsetroot -xcf /run/current-system/sw/share/icons/Bibata-Modern-Classic/cursors/left_ptr 30
wal -R &
pgrep -x sxhkd >/dev/null || sxhkd &
pkill picom
picom &
libinput-gestures &
jamesdsp --tray &
~/snix/scripts/launch-poly
xset r rate 220 40

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window Information
bspc config border_width 1
bspc config window_gap 2
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Rules
bspc rule -a mumble state=floating follow=on focus=on
