#!/bin/sh

if [[ $EUID -ne 0 ]]; then
   exec sudo "$0" "$@"
   exit 1
fi

cp /etc/nixos/hardware-configuration.nix ~/snix/nixos/hardware-configuration.nix

cd ~/snix/nixos/

sudo nixos-rebuild switch --flake .#nix-hak
