#!/bin/sh

cp /etc/nixos/hardware-configuration.nix ~/snix/nixos/hardware-configuration.nix

cd ~/snix/nixos/

nix flake update

git add . && git commit -m 's'

sudo nixos-rebuild switch --upgrade --flake .#nixos

nix store optimise
