#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_image"
    exit 1
fi

IMAGE="$1"

dunstify "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

feh --bg-fill "$IMAGE"

wal -i "$IMAGE" -n -s -t -e

# python3 "$HOME/.config/nvim/pywal/chadwal.py"

qtile cmd-obj -o cmd -f reload_config
bash $HOME/snix/scripts/ref-dunst

dunstify "Theme Applied" "Wallpaper and Theme updated successfully"
