#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

dunstify "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

feh --bg-fill "$IMAGE"

wal -i "$IMAGE" -n -s -t -e

~/snix/scripts/launch-poly
~/snix/scripts/ref-dunst

bspc wm -r
bspc wm --restart

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
